### ISSUE TITLE
Issues when running on MacOS

### ISSUE THREAD

**Issue by alchemyx** [mickygough/threatinfo#3]
Unfortunately there are errors thrown when run on MacOS, because grep doesn't have `-P` and stat doesn't have `-c` option.

```
$ ./threatinfo 127.0.0.1
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Usage: threatinfo <IPv4 ADDRESS>
```

**Comment by mickygough** [comment]
Hi alchemyx,

This should be fixed now, please update and let me know if you're still having trouble.

**Comment by mickygough** [comment]
https://github.com/mickygough/threatinfo/pull/4/commits/c4cd40ff5b26f82c15014f641d039b25115758d7

**Comment by mickygough** [comment]
Closing
